# Site settings
title: Anders Nord
email: anders-nord@live.se
description: > # this means to ignore newlines until "baseurl:"
  This is a tech blog / portfolio by Anders Nord, a software engineer and indie game developer
  living in Stockholm, Sweden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "andersnord.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  andersnord
linkedin_username: andersnord

# Build settings
#exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
highlighter: rouge
encoding: utf-8
paginate: 5

# Gems
gems: [jekyll-paginate]

# Google services
google_analytics: UA-85727178-1